### PR TITLE
Table of Contents added to consoles pages.

### PR DESCRIPTION
**Pull request by Panda-X2**
Like the title says above, table of contents have been added to the consoles pages. This encompasses links to repairs, specific questions in repairs, and mods. The Game Boy Light page has not been touched due to its incomplete nature. Some double questions were also shortened down into a single question bulletin with a forward slash.

### CODE REVIEW

**Comment by makhowastaken** [comment]
Why update the content revision dates when the content itself hasn't been updated? Adding a ToC is just a structure update and typo/grammar fixes don't update the content either.

**Comment by Panda-X2** [comment]
It helps to categorise problems individually instead of needing to read the entire page over. If you have a specific problem and you can see what it was in the table of contents, that's much quicker to check over than pouring over the entire page.

Adding a table of contents would also be useful for mods in the page too. While admittedly it hasn't been done yet, we could re-organise the mods of each console page into their own categories and then add those categories to the table of contents.

Example:

-Screen mods
-Battery mods
-Motherboard mods
-Misc. mods

And so on.

**Comment by makhowastaken** [comment]
I have no problem with adding a ToC and I agree with you on that.

Where I disagree is with the "content updates." The reason I added the dates at all was so that someone reading the page could have a quick reference to the last time someone else "verified" the actual content within. If we update that date every time the file itself gets modified, well, we should just be referencing the file modification date within github instead. As an example, since absolutes like "this is the only <x>.." are difficult to avoid, I'd prefer to proactively attach dates to statements so that when the reality changes and the information is NOT updated, the reader can still be more educated. It's a stop-gap at best and not a solution but it's better than nothing. I've read enough technical documentation from 15+ years ago to appreciate this kind of thing. 

I consider a "content update" to be something like "this mod that surfaced 2021-08-05 makes it so your pp can..." 

I do not consider a "content update" to be "the contraction 'it's' has erroneously used when the possessive 'its' should have been used." Likewise, I'm not going to go and update that date in every page every time I update the navbar even though that touches every single article on the site. 

If you want to personally vouch that all the info there is up to date, I'll merge the PR right now.

**Comment by Panda-X2** [comment]
If there is a problem with the content revision date being in conflict or misleading one to believe that content is new, then there should be no problem just editing the page to have the older content revision date.

**Pull request merged**
